const event = {
  typeName: 'Query',
  fieldName: 'getCoins',
  arguments: {},
  identity: null,
  source: null,
  request: {
    headers: {
      'x-forwarded-for': '122.170.3.194, 64.252.177.94',
      'sec-ch-ua-mobile': '?0',
      'cloudfront-viewer-country': 'IN',
      'cloudfront-is-tablet-viewer': 'false',
      'x-amzn-requestid': '95914f18-885b-42d0-906a-cca50539efc0',
      via: '2.0 16f47394e79849272b2daca917491676.cloudfront.net (CloudFront)',
      'cloudfront-forwarded-proto': 'https',
      origin: 'https://ap-south-1.console.aws.amazon.com',
      'content-length': '133',
      'x-forwarded-proto': 'https',
      host: '6z7cff3bkved7kllgrk5fmw2di.appsync-api.ap-south-1.amazonaws.com',
      'accept-language': 'en-GB,en;q=0.9',
      'user-agent':
        'Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/98.0.4758.80 Safari/537.36',
      'cloudfront-is-mobile-viewer': 'false',
      accept: 'application/json, text/plain, */*',
      'cloudfront-is-smarttv-viewer': 'false',
      'accept-encoding': 'gzip, deflate, br',
      referer: 'https://ap-south-1.console.aws.amazon.com/',
      'x-api-key': 'da2-ysvongdgtfeq3cubiu4y4wp6u4',
      'content-type': 'application/json',
      'sec-fetch-mode': 'cors',
      'x-amzn-trace-id': 'Root=1-620516ec-6539509d70a5cb1a6612886c',
      'x-amz-cf-id': 'YG_wHrMr1FAwa9-D1wZlppr7I2sxlCf2eKBT7vy_BXORHzQrFtXuFQ==',
      'sec-fetch-dest': 'empty',
      'x-amz-user-agent': 'AWS-Console-AppSync/',
      'sec-ch-ua-platform': '"Linux"',
      'cloudfront-is-desktop-viewer': 'true',
      'sec-fetch-site': 'cross-site',
      'sec-ch-ua':
        '" Not A;Brand";v="99", "Chromium";v="98", "Google Chrome";v="98"',
      'x-forwarded-port': '443',
    },
    domainName: null,
  },
  prev: { result: {} },
};
